language: csharp
sudo: required
mono: none
dist: xenial
env:
  global:
    # get all the branches referencing this commit
    - REAL_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")
    # or check if we are on a particular branch:
    - IS_RELEASE=$(git ls-remote origin | grep "$TRAVIS_COMMIT\s\+refs/heads/release$")
before_install:
  - nvm install node
install:
script:
  - echo "do scripts"
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $REAL_BRANCH
  - echo $IS_RELEASE
  - echo "end scripts"
deploy:
  - provider: script
    script: 
      echo "dev...."; echo $TRAVIS_BRANCH;echo $TRAVIS_TAG;echo $TRAVIS_PULL_REQUEST_BRANCH;echo $REAL_BRANCH;echo $IS_RELEASE
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$REAL_BRANCH = dev" AND "$TRAVIS_OS_NAME = linux"
  - provider: script
    script:
      echo "master..."
    on:
      tags: true
      all_branches: true
      condition: "$REAL_BRANCH =~ ^master|release-*$" AND "$TRAVIS_OS_NAME = linux"
 
