language: csharp
sudo: required
mono: none
dist: xenial
before_install:
  - nvm install node
  - npm install -g yarn
install:
script:
  - echo "do scripts"
  - echo $TRAVIS_BRANCH
deploy:
  - provider: script
    script: 
      echo "dev...."; echo $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_BRANCH = dev
  - provider: script
    script:
      echo "master..."
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|release-*$
