version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  verbosity: minimal
  
install:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-win32.zip', 'c:\protoc-3.6.1-win32.zip')
  - cmd: unzip c:\protoc-3.6.1-win32.zip  -d c:\
  - cmd: copy c:\bin\protoc.exe   c:\Windows

  
build_script:
  - ps: dotnet --info
  - ps: dotnet --info
  - ps: dotnet restore AElf.Console.sln
  - ps: dotnet build AElf.Console.sln
  - ps: dotnet restore AElf.sln
  - ps: dotnet build AElf.sln
  - ps: dotnet restore AElf.Management.sln
  - ps: dotnet build AElf.Management.sln
