version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2015

build:
  publish_nuget: true
  verbosity: minimal
  
install:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-win64.zip', 'c:\protoc-3.7.0-win64.zip')
  - cmd: unzip c:\protoc-3.7.0-win64.zip  -d c:\
  - cmd: copy c:\bin\protoc.exe   c:\Windows
  - cmd: node --version

  
build_script:
  - ps: dotnet build AElf.Console.sln
  - ps: $?
  - ps: $?
  - ps: dotnet test --no-build AElf.Console.sln
  - ps: $lastExitCode
  - ps: dotnet build AElf.sln
  - ps: dotnet test AElf.sln
  - ps: dotnet build AElf.Management.sln
  - ps: dotnet test AElf.Management.sln
