version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
configuration:
  - Debug
platform:
  - Any CPU
install:
  - choco install vcredist2017
  - ps: dotnet --info
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-win64.zip', 'c:\protoc-3.7.0-win64.zip')
  - cmd: dir c:\
  - cmd: unzip c:\protoc-3.7.0-win64.zip  -d c:\
  - cmd: copy c:\bin\protoc.exe   c:\Windows

  
build_script:
  - cmd: dotnet build AElf.Console.sln
  - cmd: dotnet test AElf.Console.sln
  - cmd: dotnet build AElf.sln
  - cmd: dotnet test AElf.sln
  - cmd: dotnet build AElf.Management.sln
  - cmd: dotnet test AElf.Management.sln
