version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
build:
  publish_nuget: true
  verbosity: minimal
  
install:
  - ps: dotnet --info
  - ps: (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe', 'c:\vc_redist.x64.exe')
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-win64.zip', 'c:\protoc-3.7.0-win64.zip')
  - cmd: dir c:\
  - cmd: unzip c:\protoc-3.7.0-win64.zip  -d c:\
  - cmd: copy c:\bin\protoc.exe   c:\Windows
  - cmd: node --version
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

  
build_script:
  - ps: dotnet build AElf.Console.sln
  - ps: $?
  - ps: dotnet test AElf.Console.sln
  - ps: $lastExitCode
  - ps: dotnet build AElf.sln
  - ps: dotnet test AElf.sln
  - ps: dotnet build AElf.Management.sln
  - ps: dotnet test AElf.Management.sln
